baseurl: /ebola-dashboard
permalink: pretty
permalink: /:categories/:year/:month/:day/
prose:
  rooturl: '_posts'
  relativeLinks: 'http://devseed.com/ebola-dashboard/links.jsonp'
  media: 'media'
  metadata:
    _posts:
      - name: "category"
        field:
          element: "hidden"
          value: "situation-report"
      - name: "layout"
        field:
          element: "hidden"
          value: "situation-report"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "Situation Report"
              value: "situation-report"
            - name: "Update"
              value: "update"
